name: tests

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

env:
  HYPHEN_PUBLIC_API_KEY: ${{ secrets.HYPHEN_PUBLIC_API_KEY }}
  HYPHEN_APPLICATION_ID: ${{ secrets.HYPHEN_APPLICATION_ID }}

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ['20', '22']

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install Dependencies
      run: npm install pnpm -g && pnpm install

    - name: Build    
      run: pnpm build

    - name: Testing    
      run: pnpm test

